[package]
name = "lindera-tantivy"
version = "0.1.1"
authors = ["Minoru Osuka <minoru.osuka@gmail.com>"]
edition = "2018"
description = "A Tokenizer for Tantivy, based on Lindera."
documentation = "https://docs.rs/lindera-tantivy"
homepage = "https://github.com/lindera-morphology/lindera-tantivy"
repository = "https://github.com/lindera-morphology/lindera-tantivy"
readme = "README.md"
keywords = ["tokenizer", "tantivy", "lindera"]
categories = ["text-processing"]
license = "MIT"

[dependencies]
tantivy = "0.12.0"

lindera = "0.3.5"
