[package]
name = "lindera-tantivy"
version = "0.6.0"
authors = [
    "Minoru Osuka <minoru.osuka@gmail.com>",
    "@ken0x0a",
    "Jun Ohtani <johtani@gmail.com>"
]
edition = "2018"
description = "A Tokenizer for Tantivy, based on Lindera."
documentation = "https://docs.rs/lindera-tantivy"
homepage = "https://github.com/lindera-morphology/lindera-tantivy"
repository = "https://github.com/lindera-morphology/lindera-tantivy"
readme = "README.md"
keywords = ["tokenizer", "tantivy", "lindera"]
categories = ["text-processing"]
license = "MIT"

[dependencies]
tantivy = "0.13"

lindera = "0.6"
lindera-core = "0.6"
